echo "Hi, I'm Nitesh Oswal!"
echo "I'm a young, honest, energetic individual who loves to work on several things in parallel. I'm the guy who'll try to exceed your expectations to improve & scale your startup/business to its maximum potential."
echo "---"
echo "> Hire me: https://nit.sh/upwork?ref=docker"
echo "> Size me up: https://nit.sh/github?ref=docker"
echo "> Stalk me professionally: https://nit.sh/linkedin?ref=docker"
echo "> Stalk me un-professionally: https://nit.sh/instagram?ref=docker"
echo "> Message me the old fashioned way: https://nit.sh/contact?ref=docker"
echo "---"
echo "Choose wisely!"
